### ISSUE TITLE
concatenate of contiguous slice can be optimized to a slice

### ISSUE THREAD

**Issue by avik-pal** [EnzymeAD/Enzyme-JAX#164]
```mlir
Module:
module attributes {transform.with_named_sequence} {
  func.func @main(%arg0: tensor<4x4xf32>) -> tensor<4x4xf32> {
    %0 = stablehlo.transpose %arg0, dims = [1, 0] : (tensor<4x4xf32>) -> tensor<4x4xf32>
    %1 = stablehlo.slice %0 [0:4, 0:1] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %2 = stablehlo.slice %0 [0:4, 1:2] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %3 = stablehlo.slice %0 [0:4, 2:3] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %4 = stablehlo.slice %0 [0:4, 3:4] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %5 = stablehlo.concatenate %1, %2, %3, %4, dim = 1 : (tensor<4x1xf32>, tensor<4x1xf32>, tensor<4x1xf32>, tensor<4x1xf32>) -> tensor<4x4xf32>
    %6 = stablehlo.transpose %5, dims = [1, 0] : (tensor<4x4xf32>) -> tensor<4x4xf32>
    return %6 : tensor<4x4xf32>
  }
}
```

This is a very special case, we the entire operation can be optimized way with `%6 = %0`. The following is a partial slice and concat which is common for Embedding layers (example picked from nanoGPT)

```mlir
Module:
module attributes {transform.with_named_sequence} {
  func.func @main(%arg0: tensor<4x4xf32>) -> tensor<3x4xf32> {
    %0 = stablehlo.transpose %arg0, dims = [1, 0] : (tensor<4x4xf32>) -> tensor<4x4xf32>
    %1 = stablehlo.slice %0 [0:4, 0:1] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %2 = stablehlo.slice %0 [0:4, 1:2] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %3 = stablehlo.slice %0 [0:4, 2:3] : (tensor<4x4xf32>) -> tensor<4x1xf32>
    %4 = stablehlo.concatenate %1, %2, %3, dim = 1 : (tensor<4x1xf32>, tensor<4x1xf32>, tensor<4x1xf32>) -> tensor<4x3xf32>
    %5 = stablehlo.transpose %4, dims = [1, 0] : (tensor<4x3xf32>) -> tensor<3x4xf32>
    return %5 : tensor<3x4xf32>
  }
}
```

**Comment by wsmoses** [comment]
I think the more general form of this is as follows: 
If two subsequent operands to a concat are continguous slices of the same operand used only once, we can replace the concat with a new concat where those two slices are replaced with a contiguous slice of the two. Ideally it's written in a way that checks for N slices together rather than iteratively removing pairs of slices, but that should work to still fuse the %1 and %2 in the second case, as well as fixing the first

**Comment by wsmoses** [comment]
and we already have the last step which is an optimization that a concat of a single thing -> the single elem, iirc

**Comment by mofeing** [comment]
> If two subsequent operands to a concat are continguous slices of the same operand used only once, we can replace the concat with a new concat where those two slices are replaced with a contiguous slice of the two

it seems like there are several ops that fulfill this same pattern: if 2 contiguous same ops act over the same data, then merge them into 1 op. maybe we can do one common interface and implement a common optimization pass? I know there are some opt passes already by @Pangoraw that do this but are limited to specific ops on each case.
