### ISSUE TITLE
Not working for 3.11

### ISSUE THREAD

**Issue by martinjm97** [EnzymeAD/Enzyme-JAX#5]
ImportError: Python version mismatch: module was compiled for Python 3.10, but the interpreter version is incompatible: 3.11.3 (main, Apr 19 2023, 18:51:09) [Clang 14.0.6 ].

**Comment by croci** [comment]
Same problem here.

**Comment by wsmoses** [comment]
After a bunch of stuff, we've now finally fixed our CI to auto release packages for python [3.10, 11, 12] x [aarch64, x86] x [linux, mac]

So all is resolved, hopefully (and sorry for the long lead time).
